name: ${name}
main: net.willhastings.StackJoinLeave.Main
version: ${version}
author: bill1993

commands:
  stackjoinleave:
    aliases: [sjl]
    description: Used to toggle the stacked join/leave messages on, and off.